# Generated by Django 5.0.1 on 2024-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
