# Generated by Django 5.0.1 on 2024-02-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_state_alter_patients_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='District')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.state')),
            ],
        ),
    ]
