# Generated by Django 5.0.1 on 2024-02-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
